import axios from 'axios'

const cityData = [
  {
    value: '湖南省',
    label: '湖南省',
    children: [
      {
        value: '长沙市',
        label: '长沙市',
        children: [
          { value: '宁乡市', label: '宁乡市' },
          { value: '雨花区', label: '雨花区' },
          { value: '岳麓区', label: '岳麓区' },
          { value: '天心区', label: '天心区' },
          { value: '开福区', label: '开福区' },
          { value: '浏阳市', label: '浏阳市' },
          { value: '长沙县', label: '长沙县' },
          { value: '芙蓉区', label: '芙蓉区' },
          { value: '市辖区', label: '市辖区' },
          { value: '望城区', label: '望城区' },
        ],
      },
      { value: '张家界市', label: '张家界市', children: [{ value: '永定区', label: '永定区' }] },
      {
        value: '怀化市',
        label: '怀化市',
        children: [
          { value: '鹤城区', label: '鹤城区' },
          { value: '新晃侗族自治县', label: '新晃侗族自治县' },
        ],
      },
      {
        value: '邵阳市',
        label: '邵阳市',
        children: [
          { value: '大祥区', label: '大祥区' },
          { value: '双清区', label: '双清区' },
        ],
      },
      {
        value: '岳阳市',
        label: '岳阳市',
        children: [
          { value: '岳阳楼区', label: '岳阳楼区' },
          { value: '平江县', label: '平江县' },
        ],
      },
      { value: '湘潭市', label: '湘潭市', children: [{ value: '岳塘区', label: '岳塘区' }] },
      { value: '郴州市', label: '郴州市', children: [{ value: '北湖区', label: '北湖区' }] },
      { value: '娄底市', label: '娄底市', children: [{ value: '娄星区', label: '娄星区' }] },
      {
        value: '常德市',
        label: '常德市',
        children: [
          { value: '鼎城区', label: '鼎城区' },
          { value: '武陵区', label: '武陵区' },
        ],
      },
      {
        value: '株洲市',
        label: '株洲市',
        children: [
          { value: '天元区', label: '天元区' },
          { value: '石峰区', label: '石峰区' },
          { value: '醴陵市', label: '醴陵市' },
          { value: '荷塘区', label: '荷塘区' },
        ],
      },
      {
        value: '衡阳市',
        label: '衡阳市',
        children: [
          { value: '珠晖区', label: '珠晖区' },
          { value: '蒸湘区', label: '蒸湘区' },
          { value: '石鼓区', label: '石鼓区' },
          { value: '耒阳市', label: '耒阳市' },
          { value: '衡阳县', label: '衡阳县' },
          { value: '常宁市', label: '常宁市' },
        ],
      },
      { value: '永州市', label: '永州市', children: [{ value: '冷水滩区', label: '冷水滩区' }] },
      {
        value: '益阳市',
        label: '益阳市',
        children: [
          { value: '赫山区', label: '赫山区' },
          { value: '沅江市', label: '沅江市' },
        ],
      },
      {
        value: '湘西土家族苗族自治州',
        label: '湘西土家族苗族自治州',
        children: [{ value: '吉首市', label: '吉首市' }],
      },
    ],
  },
  {
    value: '广东省',
    label: '广东省',
    children: [
      {
        value: '揭阳市',
        label: '揭阳市',
        children: [
          { value: '普宁市', label: '普宁市' },
          { value: '榕城区', label: '榕城区' },
        ],
      },
      {
        value: '潮州市',
        label: '潮州市',
        children: [
          { value: '湘桥区', label: '湘桥区' },
          { value: '潮安区', label: '潮安区' },
          { value: '饶平县', label: '饶平县' },
        ],
      },
      {
        value: '佛山市',
        label: '佛山市',
        children: [
          { value: '南海区', label: '南海区' },
          { value: '顺德区', label: '顺德区' },
          { value: '禅城区', label: '禅城区' },
          { value: '高明区', label: '高明区' },
        ],
      },
      {
        value: '深圳市',
        label: '深圳市',
        children: [
          { value: '南山区', label: '南山区' },
          { value: '龙岗区', label: '龙岗区' },
          { value: '福田区', label: '福田区' },
          { value: '宝安区', label: '宝安区' },
          { value: '罗湖区', label: '罗湖区' },
          { value: '龙华区', label: '龙华区' },
          { value: '坪山区', label: '坪山区' },
          { value: '盐田区', label: '盐田区' },
        ],
      },
      {
        value: '广州市',
        label: '广州市',
        children: [
          { value: '天河区', label: '天河区' },
          { value: '增城区', label: '增城区' },
          { value: '黄埔区', label: '黄埔区' },
          { value: '南沙区', label: '南沙区' },
          { value: '海珠区', label: '海珠区' },
          { value: '越秀区', label: '越秀区' },
          { value: '白云区', label: '白云区' },
          { value: '番禺区', label: '番禺区' },
          { value: '荔湾区', label: '荔湾区' },
          { value: '花都区', label: '花都区' },
        ],
      },
      {
        value: '惠州市',
        label: '惠州市',
        children: [
          { value: '惠城区', label: '惠城区' },
          { value: '惠东县', label: '惠东县' },
          { value: '惠阳区', label: '惠阳区' },
        ],
      },
      {
        value: '江门市',
        label: '江门市',
        children: [
          { value: '新会区', label: '新会区' },
          { value: '蓬江区', label: '蓬江区' },
        ],
      },
      { value: '云浮市', label: '云浮市', children: [{ value: '云城区', label: '云城区' }] },
      {
        value: '阳江市',
        label: '阳江市',
        children: [
          { value: '阳东区', label: '阳东区' },
          { value: '江城区', label: '江城区' },
          { value: '阳春市', label: '阳春市' },
        ],
      },
      {
        value: '茂名市',
        label: '茂名市',
        children: [
          { value: '高州市', label: '高州市' },
          { value: '信宜市', label: '信宜市' },
          { value: '茂南区', label: '茂南区' },
          { value: '化州市', label: '化州市' },
          { value: '电白区', label: '电白区' },
        ],
      },
      {
        value: '珠海市',
        label: '珠海市',
        children: [
          { value: '香洲区', label: '香洲区' },
          { value: '斗门区', label: '斗门区' },
        ],
      },
      { value: '肇庆市', label: '肇庆市', children: [{ value: '端州区', label: '端州区' }] },
      {
        value: '汕头市',
        label: '汕头市',
        children: [
          { value: '潮阳区', label: '潮阳区' },
          { value: '潮南区', label: '潮南区' },
          { value: '金平区', label: '金平区' },
        ],
      },
      {
        value: '东莞市',
        label: '东莞市',
        children: [
          { value: '东莞', label: '东莞' },
          { value: '长安区', label: '长安区' },
          { value: '东莞市', label: '东莞市' },
        ],
      },
      {
        value: '韶关市',
        label: '韶关市',
        children: [
          { value: '武江区', label: '武江区' },
          { value: '浈江区', label: '浈江区' },
        ],
      },
      {
        value: '汕尾市',
        label: '汕尾市',
        children: [
          { value: '陆丰市', label: '陆丰市' },
          { value: '海丰县', label: '海丰县' },
          { value: '城区', label: '城区' },
        ],
      },
      {
        value: '中山市',
        label: '中山市',
        children: [
          { value: '中山市', label: '中山市' },
          { value: '南区', label: '南区' },
          { value: '西区', label: '西区' },
        ],
      },
      {
        value: '湛江市',
        label: '湛江市',
        children: [
          { value: '廉江市', label: '廉江市' },
          { value: '赤坎区', label: '赤坎区' },
          { value: '雷州市', label: '雷州市' },
          { value: '霞山区', label: '霞山区' },
        ],
      },
      { value: '清远市', label: '清远市', children: [{ value: '清城区', label: '清城区' }] },
      { value: '河源市', label: '河源市', children: [{ value: '源城区', label: '源城区' }] },
      {
        value: '梅州市',
        label: '梅州市',
        children: [
          { value: '兴宁市', label: '兴宁市' },
          { value: '梅江区', label: '梅江区' },
          { value: '梅县区', label: '梅县区' },
        ],
      },
    ],
  },
  {
    value: '广西壮族自治区',
    label: '广西壮族自治区',
    children: [
      {
        value: '南宁市',
        label: '南宁市',
        children: [
          { value: '青秀区', label: '青秀区' },
          { value: '良庆区', label: '良庆区' },
        ],
      },
      {
        value: '梧州市',
        label: '梧州市',
        children: [
          { value: '藤县', label: '藤县' },
          { value: '岑溪市', label: '岑溪市' },
          { value: '长洲区', label: '长洲区' },
        ],
      },
      {
        value: '河池市',
        label: '河池市',
        children: [
          { value: '金城江区', label: '金城江区' },
          { value: '宜州区', label: '宜州区' },
        ],
      },
      { value: '贺州市', label: '贺州市', children: [{ value: '八步区', label: '八步区' }] },
      {
        value: '北海市',
        label: '北海市',
        children: [
          { value: '海城区', label: '海城区' },
          { value: '合浦县', label: '合浦县' },
        ],
      },
      {
        value: '玉林市',
        label: '玉林市',
        children: [
          { value: '玉州区', label: '玉州区' },
          { value: '北流市', label: '北流市' },
          { value: '容县', label: '容县' },
        ],
      },
      {
        value: '桂林市',
        label: '桂林市',
        children: [
          { value: '灵川县', label: '灵川县' },
          { value: '七星区', label: '七星区' },
          { value: '临桂区', label: '临桂区' },
          { value: '象山区', label: '象山区' },
          { value: '叠彩区', label: '叠彩区' },
        ],
      },
      { value: '贵港市', label: '贵港市', children: [{ value: '港北区', label: '港北区' }] },
      { value: '钦州市', label: '钦州市', children: [{ value: '钦北区', label: '钦北区' }] },
      {
        value: '柳州市',
        label: '柳州市',
        children: [
          { value: '柳北区', label: '柳北区' },
          { value: '城中区', label: '城中区' },
          { value: '鱼峰区', label: '鱼峰区' },
        ],
      },
      {
        value: '崇左市',
        label: '崇左市',
        children: [
          { value: '凭祥市', label: '凭祥市' },
          { value: '扶绥县', label: '扶绥县' },
        ],
      },
      {
        value: '百色市',
        label: '百色市',
        children: [
          { value: '右江区', label: '右江区' },
          { value: '平果市', label: '平果市' },
        ],
      },
      { value: '防城港市', label: '防城港市', children: [{ value: '港口区', label: '港口区' }] },
    ],
  },
  {
    value: '河南省',
    label: '河南省',
    children: [
      {
        value: '洛阳市',
        label: '洛阳市',
        children: [
          { value: '伊川县', label: '伊川县' },
          { value: '老城区', label: '老城区' },
          { value: '洛龙区', label: '洛龙区' },
          { value: '嵩县', label: '嵩县' },
          { value: '栾川县', label: '栾川县' },
          { value: '新安县', label: '新安县' },
          { value: '西工区', label: '西工区' },
          { value: '涧西区', label: '涧西区' },
          { value: '宜阳县', label: '宜阳县' },
        ],
      },
      {
        value: '平顶山市',
        label: '平顶山市',
        children: [
          { value: '湛河区', label: '湛河区' },
          { value: '郏县', label: '郏县' },
          { value: '新华区', label: '新华区' },
          { value: '卫东区', label: '卫东区' },
          { value: '汝州市', label: '汝州市' },
          { value: '叶县', label: '叶县' },
          { value: '鲁山县', label: '鲁山县' },
        ],
      },
      {
        value: '郑州市',
        label: '郑州市',
        children: [
          { value: '金水区', label: '金水区' },
          { value: '荥阳市', label: '荥阳市' },
          { value: '市辖区', label: '市辖区' },
          { value: '惠济区', label: '惠济区' },
          { value: '新密市', label: '新密市' },
          { value: '登封市', label: '登封市' },
          { value: '二七区', label: '二七区' },
          { value: '郑州航空港经济综合实验区', label: '郑州航空港经济综合实验区' },
          { value: '管城回族区', label: '管城回族区' },
          { value: '中原区', label: '中原区' },
          { value: '巩义市', label: '巩义市' },
          { value: '新郑市', label: '新郑市' },
        ],
      },
      {
        value: '商丘市',
        label: '商丘市',
        children: [
          { value: '夏邑县', label: '夏邑县' },
          { value: '睢阳区', label: '睢阳区' },
          { value: '民权县', label: '民权县' },
          { value: '永城市', label: '永城市' },
          { value: '柘城县', label: '柘城县' },
          { value: '市辖区', label: '市辖区' },
          { value: '梁园区', label: '梁园区' },
        ],
      },
      {
        value: '驻马店市',
        label: '驻马店市',
        children: [
          { value: '驿城区', label: '驿城区' },
          { value: '泌阳县', label: '泌阳县' },
          { value: '市辖区', label: '市辖区' },
          { value: '新蔡县', label: '新蔡县' },
        ],
      },
      {
        value: '许昌市',
        label: '许昌市',
        children: [
          { value: '长葛市', label: '长葛市' },
          { value: '建安区', label: '建安区' },
          { value: '东城区', label: '东城区' },
          { value: '禹州市', label: '禹州市' },
          { value: '魏都区', label: '魏都区' },
          { value: '鄢陵县', label: '鄢陵县' },
          { value: '许昌市', label: '许昌市' },
        ],
      },
      {
        value: '南阳市',
        label: '南阳市',
        children: [
          { value: '宛城区', label: '宛城区' },
          { value: '卧龙区', label: '卧龙区' },
          { value: '镇平县', label: '镇平县' },
          { value: '社旗县', label: '社旗县' },
          { value: '桐柏县', label: '桐柏县' },
          { value: '方城县', label: '方城县' },
          { value: '唐河县', label: '唐河县' },
          { value: '南召县', label: '南召县' },
          { value: '新野县', label: '新野县' },
          { value: '西峡县', label: '西峡县' },
        ],
      },
      {
        value: '周口市',
        label: '周口市',
        children: [
          { value: '川汇区', label: '川汇区' },
          { value: '淮阳区', label: '淮阳区' },
          { value: '郸城县', label: '郸城县' },
          { value: '项城市', label: '项城市' },
          { value: '经开区', label: '经开区' },
          { value: '沈丘县', label: '沈丘县' },
        ],
      },
      {
        value: '安阳市',
        label: '安阳市',
        children: [
          { value: '文峰区', label: '文峰区' },
          { value: '北关区', label: '北关区' },
          { value: '林州市', label: '林州市' },
        ],
      },
      {
        value: '濮阳市',
        label: '濮阳市',
        children: [
          { value: '华龙区', label: '华龙区' },
          { value: '市辖区', label: '市辖区' },
          { value: '濮阳县', label: '濮阳县' },
        ],
      },
      {
        value: '信阳市',
        label: '信阳市',
        children: [
          { value: '商城县', label: '商城县' },
          { value: '平桥区', label: '平桥区' },
          { value: '浉河区', label: '浉河区' },
          { value: '新县', label: '新县' },
          { value: '光山县', label: '光山县' },
          { value: '潢川县', label: '潢川县' },
          { value: '固始县', label: '固始县' },
        ],
      },
      {
        value: '鹤壁市',
        label: '鹤壁市',
        children: [
          { value: '淇滨区', label: '淇滨区' },
          { value: '浚县', label: '浚县' },
        ],
      },
      {
        value: '三门峡市',
        label: '三门峡市',
        children: [
          { value: '灵宝市', label: '灵宝市' },
          { value: '渑池县', label: '渑池县' },
          { value: '湖滨区', label: '湖滨区' },
          { value: '义马市', label: '义马市' },
        ],
      },
      {
        value: '新乡市',
        label: '新乡市',
        children: [
          { value: '红旗区', label: '红旗区' },
          { value: '牧野区', label: '牧野区' },
          { value: '高新区', label: '高新区' },
          { value: '新乡县', label: '新乡县' },
          { value: '长垣市', label: '长垣市' },
          { value: '原阳县', label: '原阳县' },
        ],
      },
      {
        value: '开封市',
        label: '开封市',
        children: [
          { value: '龙亭区', label: '龙亭区' },
          { value: '市辖区', label: '市辖区' },
          { value: '尉氏县', label: '尉氏县' },
          { value: '兰考县', label: '兰考县' },
        ],
      },
      {
        value: '焦作市',
        label: '焦作市',
        children: [
          { value: '温县', label: '温县' },
          { value: '解放区', label: '解放区' },
          { value: '沁阳市', label: '沁阳市' },
          { value: '山阳区', label: '山阳区' },
        ],
      },
      {
        value: '漯河市',
        label: '漯河市',
        children: [
          { value: '召陵区', label: '召陵区' },
          { value: '郾城区', label: '郾城区' },
          { value: '源汇区', label: '源汇区' },
        ],
      },
      { value: '济源市', label: '济源市', children: [{ value: '济源市', label: '济源市' }] },
    ],
  },
  {
    value: '陕西省',
    label: '陕西省',
    children: [
      {
        value: '西安市',
        label: '西安市',
        children: [
          { value: '市辖区', label: '市辖区' },
          { value: '未央区', label: '未央区' },
          { value: '雁塔区', label: '雁塔区' },
          { value: '莲湖区', label: '莲湖区' },
          { value: '临潼区', label: '临潼区' },
          { value: '新城区', label: '新城区' },
          { value: '长安区', label: '长安区' },
          { value: '碑林区', label: '碑林区' },
          { value: '高新区', label: '高新区' },
        ],
      },
      {
        value: '延安市',
        label: '延安市',
        children: [
          { value: '宝塔区', label: '宝塔区' },
          { value: '安塞区', label: '安塞区' },
        ],
      },
      {
        value: '安康市',
        label: '安康市',
        children: [
          { value: '市辖区', label: '市辖区' },
          { value: '汉滨区', label: '汉滨区' },
        ],
      },
      { value: '汉中市', label: '汉中市', children: [{ value: '汉台区', label: '汉台区' }] },
      {
        value: '榆林市',
        label: '榆林市',
        children: [
          { value: '府谷县', label: '府谷县' },
          { value: '榆阳区', label: '榆阳区' },
          { value: '神木市', label: '神木市' },
        ],
      },
      {
        value: '渭南市',
        label: '渭南市',
        children: [
          { value: '临渭区', label: '临渭区' },
          { value: '韩城市', label: '韩城市' },
        ],
      },
      {
        value: '宝鸡市',
        label: '宝鸡市',
        children: [
          { value: '市辖区', label: '市辖区' },
          { value: '渭滨区', label: '渭滨区' },
          { value: '金台区', label: '金台区' },
        ],
      },
      {
        value: '咸阳市',
        label: '咸阳市',
        children: [
          { value: '渭城区', label: '渭城区' },
          { value: '市辖区', label: '市辖区' },
          { value: '秦都区', label: '秦都区' },
        ],
      },
      { value: '商洛市', label: '商洛市', children: [{ value: '商州区', label: '商州区' }] },
    ],
  },
  {
    value: '海南省',
    label: '海南省',
    children: [
      { value: '文昌市', label: '文昌市', children: [{ value: '文昌市', label: '文昌市' }] },
      {
        value: '海口市',
        label: '海口市',
        children: [
          { value: '龙华区', label: '龙华区' },
          { value: '美兰区', label: '美兰区' },
        ],
      },
      {
        value: '琼中黎族苗族自治县',
        label: '琼中黎族苗族自治县',
        children: [{ value: '琼中黎族苗族自治县', label: '琼中黎族苗族自治县' }],
      },
      { value: '东方市', label: '东方市', children: [{ value: '东方市', label: '东方市' }] },
      {
        value: '三亚市',
        label: '三亚市',
        children: [
          { value: '海棠区', label: '海棠区' },
          { value: '吉阳区', label: '吉阳区' },
          { value: '天涯区', label: '天涯区' },
        ],
      },
      { value: '五指山市', label: '五指山市', children: [{ value: '五指山市', label: '五指山市' }] },
      { value: '儋州市', label: '儋州市', children: [{ value: '儋州市', label: '儋州市' }] },
      {
        value: '保亭黎族苗族自治县',
        label: '保亭黎族苗族自治县',
        children: [{ value: '保亭黎族苗族自治县', label: '保亭黎族苗族自治县' }],
      },
      { value: '澄迈县', label: '澄迈县', children: [{ value: '澄迈县', label: '澄迈县' }] },
      { value: '琼海市', label: '琼海市', children: [{ value: '琼海市', label: '琼海市' }] },
      { value: '万宁市', label: '万宁市', children: [{ value: '万宁市', label: '万宁市' }] },
    ],
  },
  {
    value: '北京市',
    label: '北京市',
    children: [
      {
        value: '北京市',
        label: '北京市',
        children: [
          { value: '朝阳区', label: '朝阳区' },
          { value: '大兴区', label: '大兴区' },
          { value: '门头沟区', label: '门头沟区' },
          { value: '通州区', label: '通州区' },
          { value: '丰台区', label: '丰台区' },
          { value: '平谷区', label: '平谷区' },
          { value: '怀柔区', label: '怀柔区' },
          { value: '海淀区', label: '海淀区' },
          { value: '昌平区', label: '昌平区' },
          { value: '西城区', label: '西城区' },
          { value: '东城区', label: '东城区' },
          { value: '房山区', label: '房山区' },
          { value: '延庆区', label: '延庆区' },
          { value: '顺义区', label: '顺义区' },
          { value: '石景山区', label: '石景山区' },
          { value: '密云区', label: '密云区' },
        ],
      },
    ],
  },
  {
    value: '江西省',
    label: '江西省',
    children: [
      {
        value: '南昌市',
        label: '南昌市',
        children: [
          { value: '东湖区', label: '东湖区' },
          { value: '红谷滩区', label: '红谷滩区' },
          { value: '青山湖区', label: '青山湖区' },
          { value: '西湖区', label: '西湖区' },
        ],
      },
      {
        value: '九江市',
        label: '九江市',
        children: [
          { value: '庐山市', label: '庐山市' },
          { value: '濂溪区', label: '濂溪区' },
          { value: '市辖区', label: '市辖区' },
          { value: '经济技术开发区', label: '经济技术开发区' },
          { value: '浔阳区', label: '浔阳区' },
        ],
      },
      {
        value: '赣州市',
        label: '赣州市',
        children: [
          { value: '于都县', label: '于都县' },
          { value: '瑞金市', label: '瑞金市' },
          { value: '龙南市', label: '龙南市' },
          { value: '章贡区', label: '章贡区' },
          { value: '市辖区', label: '市辖区' },
          { value: '兴国县', label: '兴国县' },
          { value: '南康区', label: '南康区' },
          { value: '安远县', label: '安远县' },
        ],
      },
      { value: '鹰潭市', label: '鹰潭市', children: [{ value: '月湖区', label: '月湖区' }] },
      { value: '吉安市', label: '吉安市', children: [{ value: '吉州区', label: '吉州区' }] },
      { value: '景德镇市', label: '景德镇市', children: [{ value: '珠山区', label: '珠山区' }] },
      { value: '抚州市', label: '抚州市', children: [{ value: '临川区', label: '临川区' }] },
      { value: '宜春市', label: '宜春市', children: [{ value: '袁州区', label: '袁州区' }] },
      { value: '新余市', label: '新余市', children: [{ value: '渝水区', label: '渝水区' }] },
      {
        value: '上饶市',
        label: '上饶市',
        children: [
          { value: '信州区', label: '信州区' },
          { value: '鄱阳县', label: '鄱阳县' },
        ],
      },
      { value: '萍乡市', label: '萍乡市', children: [{ value: '安源区', label: '安源区' }] },
    ],
  },
  {
    value: '浙江省',
    label: '浙江省',
    children: [
      {
        value: '衢州市',
        label: '衢州市',
        children: [
          { value: '柯城区', label: '柯城区' },
          { value: '衢江区', label: '衢江区' },
          { value: '开化县', label: '开化县' },
          { value: '江山市', label: '江山市' },
        ],
      },
      {
        value: '杭州市',
        label: '杭州市',
        children: [
          { value: '建德市', label: '建德市' },
          { value: '上城区', label: '上城区' },
          { value: '桐庐县', label: '桐庐县' },
          { value: '萧山区', label: '萧山区' },
          { value: '富阳区', label: '富阳区' },
          { value: '拱墅区', label: '拱墅区' },
          { value: '西湖区', label: '西湖区' },
          { value: '临安区', label: '临安区' },
          { value: '余杭区', label: '余杭区' },
          { value: '滨江区', label: '滨江区' },
          { value: '临平区', label: '临平区' },
        ],
      },
      {
        value: '台州市',
        label: '台州市',
        children: [
          { value: '路桥区', label: '路桥区' },
          { value: '玉环市', label: '玉环市' },
          { value: '椒江区', label: '椒江区' },
          { value: '温岭市', label: '温岭市' },
        ],
      },
      {
        value: '丽水市',
        label: '丽水市',
        children: [
          { value: '莲都区', label: '莲都区' },
          { value: '龙泉市', label: '龙泉市' },
        ],
      },
      {
        value: '温州市',
        label: '温州市',
        children: [
          { value: '鹿城区', label: '鹿城区' },
          { value: '龙湾区', label: '龙湾区' },
          { value: '瓯海区', label: '瓯海区' },
          { value: '乐清市', label: '乐清市' },
          { value: '瑞安市', label: '瑞安市' },
          { value: '苍南县', label: '苍南县' },
          { value: '永嘉县', label: '永嘉县' },
        ],
      },
      {
        value: '金华市',
        label: '金华市',
        children: [
          { value: '婺城区', label: '婺城区' },
          { value: '磐安县', label: '磐安县' },
          { value: '永康市', label: '永康市' },
          { value: '东阳市', label: '东阳市' },
          { value: '义乌市', label: '义乌市' },
        ],
      },
      {
        value: '湖州市',
        label: '湖州市',
        children: [
          { value: '吴兴区', label: '吴兴区' },
          { value: '德清县', label: '德清县' },
          { value: '长兴县', label: '长兴县' },
          { value: '安吉县', label: '安吉县' },
        ],
      },
      {
        value: '嘉兴市',
        label: '嘉兴市',
        children: [
          { value: '嘉善县', label: '嘉善县' },
          { value: '秀洲区', label: '秀洲区' },
          { value: '南湖区', label: '南湖区' },
          { value: '桐乡市', label: '桐乡市' },
          { value: '海宁市', label: '海宁市' },
          { value: '海盐县', label: '海盐县' },
        ],
      },
      {
        value: '宁波市',
        label: '宁波市',
        children: [
          { value: '鄞州区', label: '鄞州区' },
          { value: '海曙区', label: '海曙区' },
          { value: '慈溪市', label: '慈溪市' },
          { value: '余姚市', label: '余姚市' },
          { value: '江北区', label: '江北区' },
          { value: '镇海区', label: '镇海区' },
        ],
      },
      {
        value: '舟山市',
        label: '舟山市',
        children: [
          { value: '普陀区', label: '普陀区' },
          { value: '定海区', label: '定海区' },
        ],
      },
      {
        value: '绍兴市',
        label: '绍兴市',
        children: [
          { value: '上虞区', label: '上虞区' },
          { value: '越城区', label: '越城区' },
          { value: '柯桥区', label: '柯桥区' },
          { value: '诸暨市', label: '诸暨市' },
        ],
      },
    ],
  },
  {
    value: '山东省',
    label: '山东省',
    children: [
      {
        value: '滨州市',
        label: '滨州市',
        children: [
          { value: '沾化区', label: '沾化区' },
          { value: '邹平市', label: '邹平市' },
          { value: '博兴县', label: '博兴县' },
          { value: '滨城区', label: '滨城区' },
        ],
      },
      {
        value: '威海市',
        label: '威海市',
        children: [
          { value: '环翠区', label: '环翠区' },
          { value: '文登区', label: '文登区' },
          { value: '荣成市', label: '荣成市' },
        ],
      },
      {
        value: '济南市',
        label: '济南市',
        children: [
          { value: '天桥区', label: '天桥区' },
          { value: '章丘区', label: '章丘区' },
          { value: '莱芜区', label: '莱芜区' },
          { value: '历下区', label: '历下区' },
          { value: '历城区', label: '历城区' },
          { value: '高新区', label: '高新区' },
          { value: '市中区', label: '市中区' },
          { value: '商河县', label: '商河县' },
          { value: '槐荫区', label: '槐荫区' },
          { value: '长清区', label: '长清区' },
        ],
      },
      {
        value: '聊城市',
        label: '聊城市',
        children: [
          { value: '临清市', label: '临清市' },
          { value: '东昌府区', label: '东昌府区' },
          { value: '莘县', label: '莘县' },
          { value: '高唐县', label: '高唐县' },
          { value: '茌平区', label: '茌平区' },
          { value: '市辖区', label: '市辖区' },
          { value: '经济技术开发区', label: '经济技术开发区' },
        ],
      },
      {
        value: '淄博市',
        label: '淄博市',
        children: [
          { value: '淄川区', label: '淄川区' },
          { value: '张店区', label: '张店区' },
          { value: '沂源县', label: '沂源县' },
        ],
      },
      {
        value: '枣庄市',
        label: '枣庄市',
        children: [
          { value: '滕州市', label: '滕州市' },
          { value: '市中区', label: '市中区' },
          { value: '薛城区', label: '薛城区' },
        ],
      },
      {
        value: '日照市',
        label: '日照市',
        children: [
          { value: '东港区', label: '东港区' },
          { value: '莒县', label: '莒县' },
        ],
      },
      {
        value: '青岛市',
        label: '青岛市',
        children: [
          { value: '崂山区', label: '崂山区' },
          { value: '平度市', label: '平度市' },
          { value: '黄岛区', label: '黄岛区' },
          { value: '李沧区', label: '李沧区' },
          { value: '市北区', label: '市北区' },
          { value: '市南区', label: '市南区' },
          { value: '胶州市', label: '胶州市' },
          { value: '市辖区', label: '市辖区' },
          { value: '即墨区', label: '即墨区' },
          { value: '城阳区', label: '城阳区' },
          { value: '莱西市', label: '莱西市' },
        ],
      },
      {
        value: '烟台市',
        label: '烟台市',
        children: [
          { value: '芝罘区', label: '芝罘区' },
          { value: '蓬莱市', label: '蓬莱市' },
          { value: '莱山区', label: '莱山区' },
          { value: '福山区', label: '福山区' },
          { value: '招远市', label: '招远市' },
          { value: '龙口市', label: '龙口市' },
          { value: '栖霞市', label: '栖霞市' },
          { value: '海阳市', label: '海阳市' },
          { value: '莱阳市', label: '莱阳市' },
          { value: '莱州市', label: '莱州市' },
        ],
      },
      {
        value: '德州市',
        label: '德州市',
        children: [
          { value: '德城区', label: '德城区' },
          { value: '武城县', label: '武城县' },
          { value: '临邑县', label: '临邑县' },
          { value: '夏津县', label: '夏津县' },
        ],
      },
      {
        value: '潍坊市',
        label: '潍坊市',
        children: [
          { value: '青州市', label: '青州市' },
          { value: '高新区', label: '高新区' },
          { value: '安丘市', label: '安丘市' },
          { value: '奎文区', label: '奎文区' },
          { value: '昌邑市', label: '昌邑市' },
          { value: '寿光市', label: '寿光市' },
          { value: '诸城市', label: '诸城市' },
          { value: '昌乐县', label: '昌乐县' },
          { value: '临朐县', label: '临朐县' },
          { value: '高密市', label: '高密市' },
          { value: '潍城区', label: '潍城区' },
        ],
      },
      {
        value: '济宁市',
        label: '济宁市',
        children: [
          { value: '梁山县', label: '梁山县' },
          { value: '任城区', label: '任城区' },
          { value: '微山县', label: '微山县' },
          { value: '邹城市', label: '邹城市' },
        ],
      },
      {
        value: '临沂市',
        label: '临沂市',
        children: [
          { value: '沂水县', label: '沂水县' },
          { value: '罗庄区', label: '罗庄区' },
          { value: '兰陵县', label: '兰陵县' },
          { value: '兰山区', label: '兰山区' },
          { value: '河东区', label: '河东区' },
          { value: '费县', label: '费县' },
          { value: '沂南县', label: '沂南县' },
        ],
      },
      {
        value: '东营市',
        label: '东营市',
        children: [
          { value: '利津县', label: '利津县' },
          { value: '河口区', label: '河口区' },
          { value: '广饶县', label: '广饶县' },
          { value: '东营区', label: '东营区' },
        ],
      },
      {
        value: '泰安市',
        label: '泰安市',
        children: [
          { value: '岱岳区', label: '岱岳区' },
          { value: '新泰市', label: '新泰市' },
          { value: '泰山区', label: '泰山区' },
          { value: '肥城市', label: '肥城市' },
        ],
      },
      {
        value: '菏泽市',
        label: '菏泽市',
        children: [
          { value: '牡丹区', label: '牡丹区' },
          { value: '曹县', label: '曹县' },
        ],
      },
    ],
  },
  {
    value: '上海市',
    label: '上海市',
    children: [
      {
        value: '上海市',
        label: '上海市',
        children: [
          { value: '浦东新区', label: '浦东新区' },
          { value: '徐汇区', label: '徐汇区' },
          { value: '闵行区', label: '闵行区' },
          { value: '嘉定区', label: '嘉定区' },
          { value: '普陀区', label: '普陀区' },
          { value: '宝山区', label: '宝山区' },
          { value: '奉贤区', label: '奉贤区' },
          { value: '黄浦区', label: '黄浦区' },
          { value: '静安区', label: '静安区' },
          { value: '青浦区', label: '青浦区' },
          { value: '金山区', label: '金山区' },
          { value: '杨浦区', label: '杨浦区' },
          { value: '松江区', label: '松江区' },
          { value: '长宁区', label: '长宁区' },
          { value: '虹口区', label: '虹口区' },
        ],
      },
    ],
  },
  {
    value: '辽宁省',
    label: '辽宁省',
    children: [
      {
        value: '抚顺市',
        label: '抚顺市',
        children: [
          { value: '新抚区', label: '新抚区' },
          { value: '顺城区', label: '顺城区' },
        ],
      },
      {
        value: '大连市',
        label: '大连市',
        children: [
          { value: '瓦房店市', label: '瓦房店市' },
          { value: '沙河口区', label: '沙河口区' },
          { value: '西岗区', label: '西岗区' },
          { value: '中山区', label: '中山区' },
          { value: '金州区', label: '金州区' },
          { value: '甘井子区', label: '甘井子区' },
          { value: '旅顺口区', label: '旅顺口区' },
          { value: '庄河市', label: '庄河市' },
        ],
      },
      { value: '盘锦市', label: '盘锦市', children: [{ value: '兴隆台区', label: '兴隆台区' }] },
      { value: '朝阳市', label: '朝阳市', children: [{ value: '双塔区', label: '双塔区' }] },
      {
        value: '沈阳市',
        label: '沈阳市',
        children: [
          { value: '浑南区', label: '浑南区' },
          { value: '大东区', label: '大东区' },
          { value: '于洪区', label: '于洪区' },
          { value: '沈河区', label: '沈河区' },
          { value: '沈北新区', label: '沈北新区' },
          { value: '和平区', label: '和平区' },
          { value: '皇姑区', label: '皇姑区' },
          { value: '苏家屯区', label: '苏家屯区' },
          { value: '铁西区', label: '铁西区' },
        ],
      },
      {
        value: '营口市',
        label: '营口市',
        children: [
          { value: '大石桥市', label: '大石桥市' },
          { value: '鲅鱼圈区', label: '鲅鱼圈区' },
          { value: '站前区', label: '站前区' },
        ],
      },
      {
        value: '铁岭市',
        label: '铁岭市',
        children: [
          { value: '开原市', label: '开原市' },
          { value: '昌图县', label: '昌图县' },
          { value: '铁岭县', label: '铁岭县' },
        ],
      },
      {
        value: '锦州市',
        label: '锦州市',
        children: [
          { value: '凌河区', label: '凌河区' },
          { value: '松山区', label: '松山区' },
        ],
      },
      { value: '鞍山市', label: '鞍山市', children: [{ value: '铁东区', label: '铁东区' }] },
      { value: '葫芦岛市', label: '葫芦岛市', children: [{ value: '龙港区', label: '龙港区' }] },
      { value: '阜新市', label: '阜新市', children: [{ value: '海州区', label: '海州区' }] },
      { value: '辽阳市', label: '辽阳市', children: [{ value: '白塔区', label: '白塔区' }] },
      { value: '丹东市', label: '丹东市', children: [{ value: '振兴区', label: '振兴区' }] },
    ],
  },
  {
    value: '贵州省',
    label: '贵州省',
    children: [
      {
        value: '黔南布依族苗族自治州',
        label: '黔南布依族苗族自治州',
        children: [
          { value: '都匀市', label: '都匀市' },
          { value: '长顺县', label: '长顺县' },
          { value: '龙里县', label: '龙里县' },
          { value: '三都水族自治县', label: '三都水族自治县' },
          { value: '瓮安县', label: '瓮安县' },
          { value: '罗甸县', label: '罗甸县' },
          { value: '惠水县', label: '惠水县' },
          { value: '荔波县', label: '荔波县' },
        ],
      },
      {
        value: '贵阳市',
        label: '贵阳市',
        children: [
          { value: '云岩区', label: '云岩区' },
          { value: '观山湖区', label: '观山湖区' },
          { value: '白云区', label: '白云区' },
          { value: '花溪区', label: '花溪区' },
          { value: '息烽县', label: '息烽县' },
          { value: '开阳县', label: '开阳县' },
          { value: '修文县', label: '修文县' },
          { value: '清镇市', label: '清镇市' },
          { value: '乌当区', label: '乌当区' },
          { value: '南明区', label: '南明区' },
        ],
      },
      {
        value: '安顺市',
        label: '安顺市',
        children: [
          { value: '镇宁布依族苗族自治县', label: '镇宁布依族苗族自治县' },
          { value: '普定县', label: '普定县' },
          { value: '关岭布依族苗族自治县', label: '关岭布依族苗族自治县' },
          { value: '紫云苗族布依族自治县', label: '紫云苗族布依族自治县' },
          { value: '平坝区', label: '平坝区' },
          { value: '西秀区', label: '西秀区' },
        ],
      },
      {
        value: '铜仁市',
        label: '铜仁市',
        children: [
          { value: '碧江区', label: '碧江区' },
          { value: '松桃苗族自治县', label: '松桃苗族自治县' },
          { value: '德江县', label: '德江县' },
          { value: '思南县', label: '思南县' },
          { value: '玉屏侗族自治县', label: '玉屏侗族自治县' },
          { value: '沿河土家族自治县', label: '沿河土家族自治县' },
          { value: '万山区', label: '万山区' },
        ],
      },
      {
        value: '遵义市',
        label: '遵义市',
        children: [
          { value: '红花岗区', label: '红花岗区' },
          { value: '汇川区', label: '汇川区' },
          { value: '赤水市', label: '赤水市' },
          { value: '务川仡佬族苗族自治县', label: '务川仡佬族苗族自治县' },
          { value: '习水县', label: '习水县' },
          { value: '凤冈县', label: '凤冈县' },
          { value: '播州区', label: '播州区' },
          { value: '仁怀市', label: '仁怀市' },
          { value: '道真仡佬族苗族自治县', label: '道真仡佬族苗族自治县' },
          { value: '绥阳县', label: '绥阳县' },
          { value: '湄潭县', label: '湄潭县' },
          { value: '正安县', label: '正安县' },
        ],
      },
      {
        value: '黔东南苗族侗族自治州',
        label: '黔东南苗族侗族自治州',
        children: [
          { value: '凯里市', label: '凯里市' },
          { value: '岑巩县', label: '岑巩县' },
          { value: '麻江县', label: '麻江县' },
          { value: '天柱县', label: '天柱县' },
          { value: '榕江县', label: '榕江县' },
          { value: '镇远县', label: '镇远县' },
        ],
      },
      {
        value: '黔西南布依族苗族自治州',
        label: '黔西南布依族苗族自治州',
        children: [
          { value: '兴义市', label: '兴义市' },
          { value: '兴仁市', label: '兴仁市' },
          { value: '贞丰县', label: '贞丰县' },
          { value: '安龙县', label: '安龙县' },
        ],
      },
      {
        value: '六盘水市',
        label: '六盘水市',
        children: [
          { value: '六枝特区', label: '六枝特区' },
          { value: '钟山区', label: '钟山区' },
          { value: '盘州市', label: '盘州市' },
        ],
      },
      {
        value: '毕节市',
        label: '毕节市',
        children: [
          { value: '织金县', label: '织金县' },
          { value: '七星关区', label: '七星关区' },
          { value: '赫章县', label: '赫章县' },
          { value: '金沙县', label: '金沙县' },
          { value: '大方县', label: '大方县' },
          { value: '威宁彝族回族苗族自治县', label: '威宁彝族回族苗族自治县' },
          { value: '黔西县', label: '黔西县' },
          { value: '纳雍县', label: '纳雍县' },
        ],
      },
    ],
  },
  {
    value: '四川省',
    label: '四川省',
    children: [
      {
        value: '泸州市',
        label: '泸州市',
        children: [
          { value: '江阳区', label: '江阳区' },
          { value: '龙马潭区', label: '龙马潭区' },
          { value: '泸县', label: '泸县' },
        ],
      },
      {
        value: '成都市',
        label: '成都市',
        children: [
          { value: '武侯区', label: '武侯区' },
          { value: '彭州市', label: '彭州市' },
          { value: '高新区', label: '高新区' },
          { value: '温江区', label: '温江区' },
          { value: '成华区', label: '成华区' },
          { value: '锦江区', label: '锦江区' },
          { value: '市辖区', label: '市辖区' },
          { value: '都江堰市', label: '都江堰市' },
          { value: '双流区', label: '双流区' },
          { value: '青羊区', label: '青羊区' },
          { value: '邛崃市', label: '邛崃市' },
          { value: '崇州市', label: '崇州市' },
          { value: '天府新区', label: '天府新区' },
          { value: '金牛区', label: '金牛区' },
          { value: '简阳市', label: '简阳市' },
          { value: '龙泉驿区', label: '龙泉驿区' },
          { value: '金堂县', label: '金堂县' },
          { value: '新都区', label: '新都区' },
          { value: '郫都区', label: '郫都区' },
        ],
      },
      {
        value: '绵阳市',
        label: '绵阳市',
        children: [
          { value: '涪城区', label: '涪城区' },
          { value: '江油市', label: '江油市' },
          { value: '经开区', label: '经开区' },
          { value: '游仙区', label: '游仙区' },
        ],
      },
      { value: '广元市', label: '广元市', children: [{ value: '利州区', label: '利州区' }] },
      {
        value: '德阳市',
        label: '德阳市',
        children: [
          { value: '旌阳区', label: '旌阳区' },
          { value: '什邡市', label: '什邡市' },
          { value: '中江县', label: '中江县' },
        ],
      },
      { value: '达州市', label: '达州市', children: [{ value: '通川区', label: '通川区' }] },
      { value: '巴中市', label: '巴中市', children: [{ value: '巴州区', label: '巴州区' }] },
      {
        value: '宜宾市',
        label: '宜宾市',
        children: [
          { value: '叙州区', label: '叙州区' },
          { value: '长宁县', label: '长宁县' },
          { value: '翠屏区', label: '翠屏区' },
        ],
      },
      { value: '乐山市', label: '乐山市', children: [{ value: '市中区', label: '市中区' }] },
      { value: '资阳市', label: '资阳市', children: [{ value: '雁江区', label: '雁江区' }] },
      {
        value: '遂宁市',
        label: '遂宁市',
        children: [
          { value: '射洪市', label: '射洪市' },
          { value: '市辖区', label: '市辖区' },
        ],
      },
      {
        value: '南充市',
        label: '南充市',
        children: [
          { value: '顺庆区', label: '顺庆区' },
          { value: '南部县', label: '南部县' },
        ],
      },
      { value: '眉山市', label: '眉山市', children: [{ value: '东坡区', label: '东坡区' }] },
      { value: '凉山彝族自治州', label: '凉山彝族自治州', children: [{ value: '西昌市', label: '西昌市' }] },
      {
        value: '内江市',
        label: '内江市',
        children: [
          { value: '东兴区', label: '东兴区' },
          { value: '市中区', label: '市中区' },
        ],
      },
      { value: '自贡市', label: '自贡市', children: [{ value: '自流井区', label: '自流井区' }] },
      { value: '广安市', label: '广安市', children: [{ value: '广安区', label: '广安区' }] },
      { value: '攀枝花市', label: '攀枝花市', children: [{ value: '东区', label: '东区' }] },
    ],
  },
  {
    value: '江苏省',
    label: '江苏省',
    children: [
      {
        value: '泰州市',
        label: '泰州市',
        children: [
          { value: '海陵区', label: '海陵区' },
          { value: '高港区', label: '高港区' },
          { value: '靖江市', label: '靖江市' },
          { value: '泰兴市', label: '泰兴市' },
          { value: '兴化市', label: '兴化市' },
          { value: '姜堰区', label: '姜堰区' },
        ],
      },
      {
        value: '淮安市',
        label: '淮安市',
        children: [
          { value: '金湖县', label: '金湖县' },
          { value: '市辖区', label: '市辖区' },
          { value: '淮安区', label: '淮安区' },
          { value: '清江浦区', label: '清江浦区' },
        ],
      },
      {
        value: '无锡市',
        label: '无锡市',
        children: [
          { value: '宜兴市', label: '宜兴市' },
          { value: '梁溪区', label: '梁溪区' },
          { value: '滨湖区', label: '滨湖区' },
          { value: '新吴区', label: '新吴区' },
        ],
      },
      {
        value: '徐州市',
        label: '徐州市',
        children: [
          { value: '沛县', label: '沛县' },
          { value: '邳州市', label: '邳州市' },
          { value: '云龙区', label: '云龙区' },
          { value: '鼓楼区', label: '鼓楼区' },
          { value: '市辖区', label: '市辖区' },
          { value: '泉山区', label: '泉山区' },
        ],
      },
      {
        value: '苏州市',
        label: '苏州市',
        children: [
          { value: '姑苏区', label: '姑苏区' },
          { value: '张家港市', label: '张家港市' },
          { value: '吴江区', label: '吴江区' },
          { value: '吴中区', label: '吴中区' },
          { value: '常熟市', label: '常熟市' },
          { value: '昆山市', label: '昆山市' },
          { value: '虎丘区', label: '虎丘区' },
        ],
      },
      {
        value: '盐城市',
        label: '盐城市',
        children: [
          { value: '东台市', label: '东台市' },
          { value: '亭湖区', label: '亭湖区' },
          { value: '盐都区', label: '盐都区' },
          { value: '建湖县', label: '建湖县' },
          { value: '阜宁县', label: '阜宁县' },
        ],
      },
      {
        value: '常州市',
        label: '常州市',
        children: [
          { value: '金坛区', label: '金坛区' },
          { value: '钟楼区', label: '钟楼区' },
          { value: '溧阳市', label: '溧阳市' },
          { value: '新北区', label: '新北区' },
        ],
      },
      {
        value: '镇江市',
        label: '镇江市',
        children: [
          { value: '润州区', label: '润州区' },
          { value: '扬中市', label: '扬中市' },
          { value: '丹徒区', label: '丹徒区' },
          { value: '丹阳市', label: '丹阳市' },
          { value: '句容市', label: '句容市' },
        ],
      },
      {
        value: '南京市',
        label: '南京市',
        children: [
          { value: '秦淮区', label: '秦淮区' },
          { value: '雨花台区', label: '雨花台区' },
          { value: '鼓楼区', label: '鼓楼区' },
          { value: '江宁区', label: '江宁区' },
          { value: '浦口区', label: '浦口区' },
          { value: '建邺区', label: '建邺区' },
          { value: '玄武区', label: '玄武区' },
          { value: '溧水区', label: '溧水区' },
          { value: '六合区', label: '六合区' },
        ],
      },
      {
        value: '南通市',
        label: '南通市',
        children: [
          { value: '崇川区', label: '崇川区' },
          { value: '如皋市', label: '如皋市' },
          { value: '海安市', label: '海安市' },
          { value: '通州区', label: '通州区' },
        ],
      },
      {
        value: '扬州市',
        label: '扬州市',
        children: [
          { value: '邗江区', label: '邗江区' },
          { value: '宝应县', label: '宝应县' },
          { value: '江都区', label: '江都区' },
          { value: '高邮市', label: '高邮市' },
          { value: '仪征市', label: '仪征市' },
        ],
      },
      { value: '连云港市', label: '连云港市', children: [{ value: '海州区', label: '海州区' }] },
      { value: '宿迁市', label: '宿迁市', children: [{ value: '宿城区', label: '宿城区' }] },
    ],
  },
  {
    value: '湖北省',
    label: '湖北省',
    children: [
      {
        value: '襄阳市',
        label: '襄阳市',
        children: [
          { value: '襄州区', label: '襄州区' },
          { value: '樊城区', label: '樊城区' },
          { value: '谷城县', label: '谷城县' },
          { value: '襄城区', label: '襄城区' },
          { value: '高新技术开发区', label: '高新技术开发区' },
          { value: '老河口市', label: '老河口市' },
          { value: '枣阳市', label: '枣阳市' },
        ],
      },
      {
        value: '武汉市',
        label: '武汉市',
        children: [
          { value: '汉阳区', label: '汉阳区' },
          { value: '武昌区', label: '武昌区' },
          { value: '市辖区', label: '市辖区' },
          { value: '洪山区', label: '洪山区' },
          { value: '汉南区', label: '汉南区' },
          { value: '江岸区', label: '江岸区' },
          { value: '新洲区', label: '新洲区' },
          { value: '硚口区', label: '硚口区' },
          { value: '江汉区', label: '江汉区' },
          { value: '黄陂区', label: '黄陂区' },
        ],
      },
      {
        value: '十堰市',
        label: '十堰市',
        children: [
          { value: '房县', label: '房县' },
          { value: '茅箭区', label: '茅箭区' },
          { value: '郧西县', label: '郧西县' },
          { value: '竹山县', label: '竹山县' },
          { value: '郧阳区', label: '郧阳区' },
          { value: '丹江口市', label: '丹江口市' },
        ],
      },
      { value: '咸宁市', label: '咸宁市', children: [{ value: '咸安区', label: '咸安区' }] },
      {
        value: '荆门市',
        label: '荆门市',
        children: [
          { value: '钟祥市', label: '钟祥市' },
          { value: '东宝区', label: '东宝区' },
        ],
      },
      {
        value: '宜昌市',
        label: '宜昌市',
        children: [
          { value: '伍家岗区', label: '伍家岗区' },
          { value: '西陵区', label: '西陵区' },
          { value: '宜都市', label: '宜都市' },
          { value: '枝江市', label: '枝江市' },
        ],
      },
      {
        value: '黄冈市',
        label: '黄冈市',
        children: [
          { value: '红安县', label: '红安县' },
          { value: '麻城市', label: '麻城市' },
          { value: '黄州区', label: '黄州区' },
        ],
      },
      {
        value: '恩施土家族苗族自治州',
        label: '恩施土家族苗族自治州',
        children: [
          { value: '恩施市', label: '恩施市' },
          { value: '来凤县', label: '来凤县' },
        ],
      },
      { value: '潜江市', label: '潜江市', children: [{ value: '潜江市', label: '潜江市' }] },
      { value: '随州市', label: '随州市', children: [{ value: '曾都区', label: '曾都区' }] },
      {
        value: '孝感市',
        label: '孝感市',
        children: [
          { value: '孝南区', label: '孝南区' },
          { value: '市辖区', label: '市辖区' },
        ],
      },
      { value: '荆州市', label: '荆州市', children: [{ value: '沙市区', label: '沙市区' }] },
      { value: '仙桃市', label: '仙桃市', children: [{ value: '仙桃市', label: '仙桃市' }] },
    ],
  },
  {
    value: '重庆市',
    label: '重庆市',
    children: [
      {
        value: '重庆市',
        label: '重庆市',
        children: [
          { value: '綦江区', label: '綦江区' },
          { value: '万州区', label: '万州区' },
          { value: '九龙坡区', label: '九龙坡区' },
          { value: '南岸区', label: '南岸区' },
          { value: '南川区', label: '南川区' },
          { value: '江津区', label: '江津区' },
          { value: '渝北区', label: '渝北区' },
          { value: '渝中区', label: '渝中区' },
          { value: '开州区', label: '开州区' },
          { value: '江北区', label: '江北区' },
          { value: '潼南区', label: '潼南区' },
          { value: '涪陵区', label: '涪陵区' },
          { value: '垫江县', label: '垫江县' },
          { value: '巴南区', label: '巴南区' },
          { value: '沙坪坝区', label: '沙坪坝区' },
          { value: '璧山区', label: '璧山区' },
          { value: '北碚区', label: '北碚区' },
          { value: '铜梁区', label: '铜梁区' },
          { value: '秀山土家族苗族自治县', label: '秀山土家族苗族自治县' },
          { value: '永川区', label: '永川区' },
        ],
      },
    ],
  },
  {
    value: '天津市',
    label: '天津市',
    children: [
      {
        value: '天津市',
        label: '天津市',
        children: [
          { value: '东丽区', label: '东丽区' },
          { value: '蓟州区', label: '蓟州区' },
          { value: '滨海新区', label: '滨海新区' },
          { value: '西青区', label: '西青区' },
          { value: '南开区', label: '南开区' },
          { value: '河西区', label: '河西区' },
          { value: '宝坻区', label: '宝坻区' },
          { value: '武清区', label: '武清区' },
          { value: '静海区', label: '静海区' },
          { value: '和平区', label: '和平区' },
          { value: '河北区', label: '河北区' },
          { value: '红桥区', label: '红桥区' },
          { value: '津南区', label: '津南区' },
          { value: '北辰区', label: '北辰区' },
          { value: '河东区', label: '河东区' },
        ],
      },
    ],
  },
  {
    value: '云南省',
    label: '云南省',
    children: [
      { value: '玉溪市', label: '玉溪市', children: [{ value: '红塔区', label: '红塔区' }] },
      {
        value: '昆明市',
        label: '昆明市',
        children: [
          { value: '官渡区', label: '官渡区' },
          { value: '市辖区', label: '市辖区' },
          { value: '西山区', label: '西山区' },
          { value: '石林彝族自治县', label: '石林彝族自治县' },
          { value: '五华区', label: '五华区' },
          { value: '盘龙区', label: '盘龙区' },
          { value: '宜良县', label: '宜良县' },
          { value: '嵩明县', label: '嵩明县' },
          { value: '安宁市', label: '安宁市' },
          { value: '晋宁区', label: '晋宁区' },
          { value: '呈贡区', label: '呈贡区' },
          { value: '富民县', label: '富民县' },
        ],
      },
      { value: '大理白族自治州', label: '大理白族自治州', children: [{ value: '大理市', label: '大理市' }] },
      { value: '西双版纳傣族自治州', label: '西双版纳傣族自治州', children: [{ value: '景洪市', label: '景洪市' }] },
      { value: '楚雄彝族自治州', label: '楚雄彝族自治州', children: [{ value: '楚雄市', label: '楚雄市' }] },
      {
        value: '曲靖市',
        label: '曲靖市',
        children: [
          { value: '麒麟区', label: '麒麟区' },
          { value: '富源县', label: '富源县' },
          { value: '市辖区', label: '市辖区' },
        ],
      },
      { value: '普洱市', label: '普洱市', children: [{ value: '思茅区', label: '思茅区' }] },
      { value: '德宏傣族景颇族自治州', label: '德宏傣族景颇族自治州', children: [{ value: '芒市', label: '芒市' }] },
      { value: '昭通市', label: '昭通市', children: [{ value: '昭阳区', label: '昭阳区' }] },
      {
        value: '红河哈尼族彝族自治州',
        label: '红河哈尼族彝族自治州',
        children: [{ value: '蒙自市', label: '蒙自市' }],
      },
      { value: '文山壮族苗族自治州', label: '文山壮族苗族自治州', children: [{ value: '文山市', label: '文山市' }] },
    ],
  },
  {
    value: '甘肃省',
    label: '甘肃省',
    children: [
      { value: '张掖市', label: '张掖市', children: [{ value: '甘州区', label: '甘州区' }] },
      {
        value: '兰州市',
        label: '兰州市',
        children: [
          { value: '安宁区', label: '安宁区' },
          { value: '城关区', label: '城关区' },
          { value: '西固区', label: '西固区' },
          { value: '七里河区', label: '七里河区' },
          { value: '永登县', label: '永登县' },
        ],
      },
      { value: '定西市', label: '定西市', children: [{ value: '安定区', label: '安定区' }] },
      { value: '武威市', label: '武威市', children: [{ value: '凉州区', label: '凉州区' }] },
      { value: '临夏回族自治州', label: '临夏回族自治州', children: [{ value: '临夏市', label: '临夏市' }] },
      { value: '庆阳市', label: '庆阳市', children: [{ value: '西峰区', label: '西峰区' }] },
      {
        value: '酒泉市',
        label: '酒泉市',
        children: [
          { value: '肃州区', label: '肃州区' },
          { value: '敦煌市', label: '敦煌市' },
        ],
      },
      { value: '嘉峪关市', label: '嘉峪关市', children: [{ value: '市辖区', label: '市辖区' }] },
      {
        value: '金昌市',
        label: '金昌市',
        children: [
          { value: '永昌县', label: '永昌县' },
          { value: '金川区', label: '金川区' },
        ],
      },
      { value: '陇南市', label: '陇南市', children: [{ value: '武都区', label: '武都区' }] },
      { value: '平凉市', label: '平凉市', children: [{ value: '崆峒区', label: '崆峒区' }] },
      {
        value: '天水市',
        label: '天水市',
        children: [
          { value: '麦积区', label: '麦积区' },
          { value: '秦州区', label: '秦州区' },
        ],
      },
      { value: '白银市', label: '白银市', children: [{ value: '白银区', label: '白银区' }] },
    ],
  },
  {
    value: '吉林省',
    label: '吉林省',
    children: [
      {
        value: '白山市',
        label: '白山市',
        children: [
          { value: '浑江区', label: '浑江区' },
          { value: '临江市', label: '临江市' },
          { value: '抚松县', label: '抚松县' },
          { value: '江源区', label: '江源区' },
          { value: '靖宇县', label: '靖宇县' },
        ],
      },
      {
        value: '长春市',
        label: '长春市',
        children: [
          { value: '二道区', label: '二道区' },
          { value: '绿园区', label: '绿园区' },
          { value: '市辖区', label: '市辖区' },
          { value: '朝阳区', label: '朝阳区' },
          { value: '南关区', label: '南关区' },
        ],
      },
      {
        value: '辽源市',
        label: '辽源市',
        children: [
          { value: '龙山区', label: '龙山区' },
          { value: '西安区', label: '西安区' },
        ],
      },
      {
        value: '松原市',
        label: '松原市',
        children: [
          { value: '宁江区', label: '宁江区' },
          { value: '前郭尔罗斯蒙古族自治县', label: '前郭尔罗斯蒙古族自治县' },
        ],
      },
      {
        value: '通化市',
        label: '通化市',
        children: [
          { value: '东昌区', label: '东昌区' },
          { value: '辉南县', label: '辉南县' },
        ],
      },
      { value: '白城市', label: '白城市', children: [{ value: '洮北区', label: '洮北区' }] },
      {
        value: '吉林市',
        label: '吉林市',
        children: [
          { value: '昌邑区', label: '昌邑区' },
          { value: '船营区', label: '船营区' },
        ],
      },
      {
        value: '延边朝鲜族自治州',
        label: '延边朝鲜族自治州',
        children: [
          { value: '和龙市', label: '和龙市' },
          { value: '延吉市', label: '延吉市' },
        ],
      },
      {
        value: '四平市',
        label: '四平市',
        children: [
          { value: '铁东区', label: '铁东区' },
          { value: '铁西区', label: '铁西区' },
        ],
      },
    ],
  },
  {
    value: '安徽省',
    label: '安徽省',
    children: [
      {
        value: '合肥市',
        label: '合肥市',
        children: [
          { value: '肥东县', label: '肥东县' },
          { value: '庐江县', label: '庐江县' },
          { value: '蜀山区', label: '蜀山区' },
          { value: '庐阳区', label: '庐阳区' },
          { value: '包河区', label: '包河区' },
          { value: '巢湖市', label: '巢湖市' },
          { value: '瑶海区', label: '瑶海区' },
        ],
      },
      {
        value: '阜阳市',
        label: '阜阳市',
        children: [
          { value: '太和县', label: '太和县' },
          { value: '颍州区', label: '颍州区' },
          { value: '界首市', label: '界首市' },
          { value: '临泉县', label: '临泉县' },
          { value: '颍泉区', label: '颍泉区' },
        ],
      },
      {
        value: '芜湖市',
        label: '芜湖市',
        children: [
          { value: '镜湖区', label: '镜湖区' },
          { value: '无为市', label: '无为市' },
          { value: '弋江区', label: '弋江区' },
        ],
      },
      {
        value: '滁州市',
        label: '滁州市',
        children: [
          { value: '南谯区', label: '南谯区' },
          { value: '天长市', label: '天长市' },
        ],
      },
      {
        value: '安庆市',
        label: '安庆市',
        children: [
          { value: '岳西县', label: '岳西县' },
          { value: '迎江区', label: '迎江区' },
        ],
      },
      {
        value: '宿州市',
        label: '宿州市',
        children: [
          { value: '埇桥区', label: '埇桥区' },
          { value: '泗县', label: '泗县' },
          { value: '市辖区', label: '市辖区' },
        ],
      },
      {
        value: '黄山市',
        label: '黄山市',
        children: [
          { value: '歙县', label: '歙县' },
          { value: '屯溪区', label: '屯溪区' },
        ],
      },
      { value: '铜陵市', label: '铜陵市', children: [{ value: '铜官区', label: '铜官区' }] },
      {
        value: '淮北市',
        label: '淮北市',
        children: [
          { value: '相山区', label: '相山区' },
          { value: '濉溪县', label: '濉溪县' },
        ],
      },
      {
        value: '六安市',
        label: '六安市',
        children: [
          { value: '金安区', label: '金安区' },
          { value: '裕安区', label: '裕安区' },
        ],
      },
      {
        value: '宣城市',
        label: '宣城市',
        children: [
          { value: '绩溪县', label: '绩溪县' },
          { value: '宁国市', label: '宁国市' },
          { value: '广德市', label: '广德市' },
          { value: '宣州区', label: '宣州区' },
        ],
      },
      { value: '蚌埠市', label: '蚌埠市', children: [{ value: '蚌山区', label: '蚌山区' }] },
      {
        value: '马鞍山市',
        label: '马鞍山市',
        children: [
          { value: '当涂县', label: '当涂县' },
          { value: '雨山区', label: '雨山区' },
        ],
      },
      { value: '淮南市', label: '淮南市', children: [{ value: '田家庵区', label: '田家庵区' }] },
      { value: '亳州市', label: '亳州市', children: [{ value: '谯城区', label: '谯城区' }] },
    ],
  },
  {
    value: '宁夏回族自治区',
    label: '宁夏回族自治区',
    children: [
      {
        value: '银川市',
        label: '银川市',
        children: [
          { value: '贺兰县', label: '贺兰县' },
          { value: '兴庆区', label: '兴庆区' },
          { value: '金凤区', label: '金凤区' },
          { value: '西夏区', label: '西夏区' },
        ],
      },
      { value: '固原市', label: '固原市', children: [{ value: '原州区', label: '原州区' }] },
      { value: '吴忠市', label: '吴忠市', children: [{ value: '利通区', label: '利通区' }] },
      { value: '中卫市', label: '中卫市', children: [{ value: '沙坡头区', label: '沙坡头区' }] },
      { value: '石嘴山市', label: '石嘴山市', children: [{ value: '大武口区', label: '大武口区' }] },
    ],
  },
  {
    value: '河北省',
    label: '河北省',
    children: [
      {
        value: '石家庄市',
        label: '石家庄市',
        children: [
          { value: '长安区', label: '长安区' },
          { value: '藁城区', label: '藁城区' },
          { value: '裕华区', label: '裕华区' },
          { value: '桥西区', label: '桥西区' },
          { value: '鹿泉区', label: '鹿泉区' },
          { value: '无极县', label: '无极县' },
          { value: '新华区', label: '新华区' },
          { value: '新乐市', label: '新乐市' },
          { value: '正定县', label: '正定县' },
        ],
      },
      {
        value: '廊坊市',
        label: '廊坊市',
        children: [
          { value: '固安县', label: '固安县' },
          { value: '霸州市', label: '霸州市' },
          { value: '广阳区', label: '广阳区' },
          { value: '三河市', label: '三河市' },
          { value: '安次区', label: '安次区' },
        ],
      },
      {
        value: '保定市',
        label: '保定市',
        children: [
          { value: '竞秀区', label: '竞秀区' },
          { value: '安新县', label: '安新县' },
          { value: '容城县', label: '容城县' },
          { value: '莲池区', label: '莲池区' },
          { value: '涿州市', label: '涿州市' },
          { value: '高碑店市', label: '高碑店市' },
          { value: '高阳县', label: '高阳县' },
          { value: '定州市', label: '定州市' },
        ],
      },
      { value: '张家口市', label: '张家口市', children: [{ value: '宣化区', label: '宣化区' }] },
      {
        value: '沧州市',
        label: '沧州市',
        children: [
          { value: '任丘市', label: '任丘市' },
          { value: '运河区', label: '运河区' },
          { value: '河间市', label: '河间市' },
          { value: '泊头市', label: '泊头市' },
          { value: '黄骅市', label: '黄骅市' },
          { value: '新华区', label: '新华区' },
        ],
      },
      {
        value: '秦皇岛市',
        label: '秦皇岛市',
        children: [
          { value: '北戴河区', label: '北戴河区' },
          { value: '海港区', label: '海港区' },
          { value: '昌黎县', label: '昌黎县' },
        ],
      },
      {
        value: '邯郸市',
        label: '邯郸市',
        children: [
          { value: '丛台区', label: '丛台区' },
          { value: '武安市', label: '武安市' },
          { value: '邯山区', label: '邯山区' },
        ],
      },
      {
        value: '邢台市',
        label: '邢台市',
        children: [
          { value: '信都区', label: '信都区' },
          { value: '宁晋县', label: '宁晋县' },
          { value: '任县', label: '任县' },
          { value: '巨鹿县', label: '巨鹿县' },
        ],
      },
      {
        value: '衡水市',
        label: '衡水市',
        children: [
          { value: '桃城区', label: '桃城区' },
          { value: '市辖区', label: '市辖区' },
          { value: '枣强县', label: '枣强县' },
        ],
      },
      {
        value: '唐山市',
        label: '唐山市',
        children: [
          { value: '路北区', label: '路北区' },
          { value: '迁安市', label: '迁安市' },
          { value: '丰润区', label: '丰润区' },
          { value: '迁西县', label: '迁西县' },
          { value: '滦州市', label: '滦州市' },
          { value: '遵化市', label: '遵化市' },
        ],
      },
      { value: '承德市', label: '承德市', children: [{ value: '双桥区', label: '双桥区' }] },
    ],
  },
  {
    value: '山西省',
    label: '山西省',
    children: [
      { value: '忻州市', label: '忻州市', children: [{ value: '市辖区', label: '市辖区' }] },
      {
        value: '太原市',
        label: '太原市',
        children: [
          { value: '万柏林区', label: '万柏林区' },
          { value: '小店区', label: '小店区' },
          { value: '晋源区', label: '晋源区' },
          { value: '市辖区', label: '市辖区' },
          { value: '迎泽区', label: '迎泽区' },
          { value: '杏花岭区', label: '杏花岭区' },
        ],
      },
      { value: '大同市', label: '大同市', children: [{ value: '平城区', label: '平城区' }] },
      {
        value: '运城市',
        label: '运城市',
        children: [
          { value: '盐湖区', label: '盐湖区' },
          { value: '河津市', label: '河津市' },
        ],
      },
      { value: '吕梁市', label: '吕梁市', children: [{ value: '离石区', label: '离石区' }] },
      { value: '朔州市', label: '朔州市', children: [{ value: '朔城区', label: '朔城区' }] },
      { value: '晋城市', label: '晋城市', children: [{ value: '城区', label: '城区' }] },
      { value: '临汾市', label: '临汾市', children: [{ value: '尧都区', label: '尧都区' }] },
      { value: '晋中市', label: '晋中市', children: [{ value: '榆次区', label: '榆次区' }] },
      {
        value: '阳泉市',
        label: '阳泉市',
        children: [
          { value: '城区', label: '城区' },
          { value: '郊区', label: '郊区' },
        ],
      },
      { value: '长治市', label: '长治市', children: [{ value: '潞州区', label: '潞州区' }] },
    ],
  },
  {
    value: '内蒙古自治区',
    label: '内蒙古自治区',
    children: [
      { value: '巴彦淖尔市', label: '巴彦淖尔市', children: [{ value: '临河区', label: '临河区' }] },
      {
        value: '呼和浩特市',
        label: '呼和浩特市',
        children: [
          { value: '赛罕区', label: '赛罕区' },
          { value: '新城区', label: '新城区' },
          { value: '市辖区', label: '市辖区' },
        ],
      },
      { value: '兴安盟', label: '兴安盟', children: [{ value: '乌兰浩特市', label: '乌兰浩特市' }] },
      {
        value: '包头市',
        label: '包头市',
        children: [
          { value: '青山区', label: '青山区' },
          { value: '昆都仑区', label: '昆都仑区' },
        ],
      },
      {
        value: '鄂尔多斯市',
        label: '鄂尔多斯市',
        children: [
          { value: '东胜区', label: '东胜区' },
          { value: '康巴什区', label: '康巴什区' },
        ],
      },
      {
        value: '赤峰市',
        label: '赤峰市',
        children: [
          { value: '喀喇沁旗', label: '喀喇沁旗' },
          { value: '红山区', label: '红山区' },
        ],
      },
      { value: '通辽市', label: '通辽市', children: [{ value: '科尔沁区', label: '科尔沁区' }] },
      { value: '阿拉善盟', label: '阿拉善盟', children: [{ value: '阿拉善左旗', label: '阿拉善左旗' }] },
      { value: '乌海市', label: '乌海市', children: [{ value: '海勃湾区', label: '海勃湾区' }] },
      { value: '乌兰察布市', label: '乌兰察布市', children: [{ value: '集宁区', label: '集宁区' }] },
      {
        value: '呼伦贝尔市',
        label: '呼伦贝尔市',
        children: [
          { value: '满洲里市', label: '满洲里市' },
          { value: '海拉尔区', label: '海拉尔区' },
        ],
      },
    ],
  },
  {
    value: '福建省',
    label: '福建省',
    children: [
      {
        value: '三明市',
        label: '三明市',
        children: [
          { value: '梅列区', label: '梅列区' },
          { value: '三元区', label: '三元区' },
        ],
      },
      {
        value: '厦门市',
        label: '厦门市',
        children: [
          { value: '湖里区', label: '湖里区' },
          { value: '思明区', label: '思明区' },
          { value: '海沧区', label: '海沧区' },
        ],
      },
      {
        value: '龙岩市',
        label: '龙岩市',
        children: [
          { value: '连城县', label: '连城县' },
          { value: '长汀县', label: '长汀县' },
          { value: '新罗区', label: '新罗区' },
        ],
      },
      {
        value: '南平市',
        label: '南平市',
        children: [
          { value: '延平区', label: '延平区' },
          { value: '武夷山市', label: '武夷山市' },
        ],
      },
      {
        value: '泉州市',
        label: '泉州市',
        children: [
          { value: '晋江市', label: '晋江市' },
          { value: '丰泽区', label: '丰泽区' },
          { value: '安溪县', label: '安溪县' },
          { value: '市辖区', label: '市辖区' },
          { value: '石狮市', label: '石狮市' },
          { value: '惠安县', label: '惠安县' },
          { value: '永春县', label: '永春县' },
        ],
      },
      {
        value: '福州市',
        label: '福州市',
        children: [
          { value: '鼓楼区', label: '鼓楼区' },
          { value: '闽侯县', label: '闽侯县' },
          { value: '晋安区', label: '晋安区' },
          { value: '台江区', label: '台江区' },
          { value: '仓山区', label: '仓山区' },
        ],
      },
      {
        value: '莆田市',
        label: '莆田市',
        children: [
          { value: '城厢区', label: '城厢区' },
          { value: '秀屿区', label: '秀屿区' },
          { value: '荔城区', label: '荔城区' },
        ],
      },
      {
        value: '漳州市',
        label: '漳州市',
        children: [
          { value: '龙海市', label: '龙海市' },
          { value: '芗城区', label: '芗城区' },
        ],
      },
      {
        value: '宁德市',
        label: '宁德市',
        children: [
          { value: '蕉城区', label: '蕉城区' },
          { value: '福安市', label: '福安市' },
        ],
      },
    ],
  },
  {
    value: '新疆维吾尔自治区',
    label: '新疆维吾尔自治区',
    children: [
      {
        value: '巴音郭楞蒙古自治州',
        label: '巴音郭楞蒙古自治州',
        children: [{ value: '库尔勒市', label: '库尔勒市' }],
      },
      {
        value: '乌鲁木齐市',
        label: '乌鲁木齐市',
        children: [
          { value: '新市区', label: '新市区' },
          { value: '头屯河区', label: '头屯河区' },
          { value: '水磨沟区', label: '水磨沟区' },
          { value: '沙依巴克区', label: '沙依巴克区' },
          { value: '米东区', label: '米东区' },
          { value: '天山区', label: '天山区' },
        ],
      },
      { value: '石河子市', label: '石河子市', children: [{ value: '石河子市', label: '石河子市' }] },
      {
        value: '伊犁哈萨克自治州',
        label: '伊犁哈萨克自治州',
        children: [
          { value: '伊宁市', label: '伊宁市' },
          { value: '奎屯市', label: '奎屯市' },
        ],
      },
      { value: '喀什地区', label: '喀什地区', children: [{ value: '喀什市', label: '喀什市' }] },
      { value: '克拉玛依市', label: '克拉玛依市', children: [{ value: '克拉玛依区', label: '克拉玛依区' }] },
      { value: '昌吉回族自治州', label: '昌吉回族自治州', children: [{ value: '昌吉市', label: '昌吉市' }] },
      { value: '阿勒泰地区', label: '阿勒泰地区', children: [{ value: '阿勒泰市', label: '阿勒泰市' }] },
      { value: '哈密市', label: '哈密市', children: [{ value: '伊州区', label: '伊州区' }] },
      { value: '和田地区', label: '和田地区', children: [{ value: '和田市', label: '和田市' }] },
    ],
  },
  {
    value: '黑龙江省',
    label: '黑龙江省',
    children: [
      {
        value: '大庆市',
        label: '大庆市',
        children: [
          { value: '让胡路区', label: '让胡路区' },
          { value: '龙凤区', label: '龙凤区' },
          { value: '萨尔图区', label: '萨尔图区' },
        ],
      },
      {
        value: '哈尔滨市',
        label: '哈尔滨市',
        children: [
          { value: '南岗区', label: '南岗区' },
          { value: '道里区', label: '道里区' },
          { value: '呼兰区', label: '呼兰区' },
          { value: '松北区', label: '松北区' },
        ],
      },
      { value: '佳木斯市', label: '佳木斯市', children: [{ value: '前进区', label: '前进区' }] },
      { value: '大兴安岭地区', label: '大兴安岭地区', children: [{ value: '加格达奇区', label: '加格达奇区' }] },
      { value: '鸡西市', label: '鸡西市', children: [{ value: '鸡冠区', label: '鸡冠区' }] },
      {
        value: '牡丹江市',
        label: '牡丹江市',
        children: [
          { value: '绥芬河市', label: '绥芬河市' },
          { value: '东安区', label: '东安区' },
        ],
      },
      {
        value: '绥化市',
        label: '绥化市',
        children: [
          { value: '北林区', label: '北林区' },
          { value: '肇东市', label: '肇东市' },
        ],
      },
      { value: '双鸭山市', label: '双鸭山市', children: [{ value: '尖山区', label: '尖山区' }] },
      { value: '齐齐哈尔市', label: '齐齐哈尔市', children: [{ value: '龙沙区', label: '龙沙区' }] },
      { value: '七台河市', label: '七台河市', children: [{ value: '桃山区', label: '桃山区' }] },
      { value: '黑河市', label: '黑河市', children: [{ value: '爱辉区', label: '爱辉区' }] },
    ],
  },
  {
    value: '青海省',
    label: '青海省',
    children: [
      {
        value: '西宁市',
        label: '西宁市',
        children: [
          { value: '城北区', label: '城北区' },
          { value: '城西区', label: '城西区' },
          { value: '城中区', label: '城中区' },
        ],
      },
      {
        value: '海西蒙古族藏族自治州',
        label: '海西蒙古族藏族自治州',
        children: [
          { value: '格尔木市', label: '格尔木市' },
          { value: '德令哈市', label: '德令哈市' },
        ],
      },
      { value: '海东市', label: '海东市', children: [{ value: '平安区', label: '平安区' }] },
    ],
  },
  {
    value: '西藏自治区',
    label: '西藏自治区',
    children: [
      {
        value: '拉萨市',
        label: '拉萨市',
        children: [
          { value: '城关区', label: '城关区' },
          { value: '堆龙德庆区', label: '堆龙德庆区' },
          { value: '经济技术开发区', label: '经济技术开发区' },
        ],
      },
      { value: '日喀则市', label: '日喀则市', children: [{ value: '桑珠孜区', label: '桑珠孜区' }] },
    ],
  },
]
export default cityData
